run:
  timeout: 300s

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

  goheader:
    template: |-
      Licensed under the Creative Commons License.

  nolintlint:
    allow-leading-space: false
    allow-unused: false
    require-specific: true

# Run `golangci-lint linters` to see the descriptions for the linters.
linters:
  disable:
    - cyclop
    - depguard
    - dupl
    - exhaustivestruct
    - forbidigo
    - funlen
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - golint
    - gomnd
    - gomodguard
    - interfacer
    - maligned
    - nlreturn
    - paralleltest
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - testpackage
    - wrapcheck
    - wsl

  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gocritic
    - goheader
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - exportloopref
    - staticcheck
    - structcheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace

issues:
  fix: true

  max-issues-per-linter: 25

  max-same-issues: 0

  exclude-rules:
    - path: (^test/.*\.go|.*_test\.go)
      linters:
        - goconst
        - scopelint
        - unparam
