#!/usr/bin/env sh

# shellcheck source=/dev/null
. "$(dirname "$0")/_/husky.sh"

printf "\n3. Lint Commit Message: (commitlint-msg)"
commitlint --config shift-left/.commitlintrc.yml --edit "$HUSKY_GIT_PARAMS"

# shellcheck disable=SC2154
cd "$current_working_dir" || return
printf "\n Done"
